// flow-typed signature: 5cc6c668a5c9b6677e74d7afecae584d
// flow-typed version: <<STUB>>/babel-plugin-transform-regenerator_v^6.16.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-regenerator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-regenerator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-regenerator/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-regenerator/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/lib/index'>;
}
